#######
it 's a charming and often affecting journey .  </s>
OVERALL SENSITIVITY ON THIS DATAPOINT 1.0848767171087184
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.9999999982304977 	 0.9391098565673828
&&&&&&&&&@ SUBSETS 	  it 's######## and often######## .</s>
&&&&&&&&&% SUBSETS 	 [["it 's", '########', 'and often', '########', '.</s>']]
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's very simple and often works well. 	 tensor([-7.7664])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's usually funny and often comical. 	 tensor([-7.7641])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very real and often has to. 	 tensor([-7.7572])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's very common and often more so. 	 tensor([-4.7796])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a complex and often tangled web. 	 tensor([-2.9503])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's a lengthy and often controversial journey. 	 tensor([-0.0684])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's quite hard and often very dangerous. 	 tensor([-0.0284])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's a long and often lonely journey. 	 tensor([-0.0019])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's very dangerous and often a nightmare. 	 tensor([-0.0011])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
it's too simple and often too bad. 	 tensor([-0.0008])
#######
it 's slow -- very , very slow .  </s>
OVERALL SENSITIVITY ON THIS DATAPOINT 1.349582402255356
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.9999999971051096 	 0.7997418725013733
&&&&&&&&&@ SUBSETS 	  it################ -- very , very#### .</s>
&&&&&&&&&% SUBSETS 	 [['it', '################', '-- very , very', '####', '.</s>']]
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it are all very happy - - very, very happy. 	 tensor([-7.7850])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it, we are very - - very, very confident. 	 tensor([-7.7848])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it's very nice - - very, very beautiful. 	 tensor([-7.7841])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it I' m very - - very, very happy. 	 tensor([-7.7813])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it felt as if it - - very, very powerful. 	 tensor([-7.7765])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very different - - very, very different. 	 tensor([-7.0539])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very simple - - very, very simple. 	 tensor([-4.1045])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it's very rare - - very, very rare. 	 tensor([-2.6072])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it wasn't surprising - - very, very surprising. 	 tensor([-2.0980])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it's my brother - - very, very different. 	 tensor([-1.0479])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it will be very long - - very, very long. 	 tensor([-0.0025])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's something fundamental - - very, very wrong. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it's not good - - very, very bad. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it . . . very - - very, very disappointing. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
it I would say it - - very, very bad. 	 tensor([-0.0008])
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.9999999952219483 	 0.5498405317687989
&&&&&&&&&@ SUBSETS 	  it 's slow######################## very slow .</s>
&&&&&&&&&% SUBSETS 	 [["it 's slow", '########################', 'very slow .</s>']]
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow, but it's not very slow. 	 tensor([-2.6297])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow for life but it's very slow. 	 tensor([-0.0018])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, but it's actually very slow. 	 tensor([-0.0010])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, and we can do that very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, but it's definitely very slow. 	 tensor([-0.0009])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow, it's very, very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow not only - it's very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - - we' re moving very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
it's slow - moving, very slow, very slow. 	 tensor([-0.0008])
#######
or doing last year 's taxes with your ex-wife .  </s>
OVERALL SENSITIVITY ON THIS DATAPOINT 0.9868425290821414
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.5000000015963606 	 0.8383353978729248
&&&&&&&&&@ SUBSETS 	  or doing last year#################################### .</s>
&&&&&&&&&% SUBSETS 	 [['or doing last year', '####################################', '.</s>']]
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year was at the top of the list, too. 	 tensor([-7.7360])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year's " Super Bowl " was pretty impressive. 	 tensor([-7.7318])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year, she found her voice in the limelight. 	 tensor([-7.6596])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year's best work: the first two movies. 	 tensor([-7.6276])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year, at the point of all our business plans. 	 tensor([-1.3803])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year's film on the set of An Education. 	 tensor([-0.2086])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year of the month . other than for business travel. 	 tensor([-0.0613])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's show in Manhattan last year? 5. 	 tensor([-0.0031])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year's version of " American Idol "). 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
or doing last year is the lowest annual rate recorded in 17 years. 	 tensor([-0.0010])
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.49999997285888775 	 0.5679957489395142
&&&&&&&&&@ SUBSETS 	  or doing######################## with your ex-wife .</s>
&&&&&&&&&% SUBSETS 	 [['or doing', '########################', 'with your ex-wife .</s>']]
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing a very good job keeping up with your ex - wife. 	 tensor([-5.3836])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing just fine? a photo opportunity with your ex - wife. 	 tensor([-1.8499])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something similar, or even corresponding with your ex - wife. 	 tensor([-1.2264])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing something " good " than that with your ex - wife. 	 tensor([-0.4141])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing you want in a private life with your ex - wife. 	 tensor([-0.1325])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing the same sex in a relationship with your ex - wife. 	 tensor([-0.0038])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing it for a whole short time with your ex - wife. 	 tensor([-0.0026])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing so because you have a dispute with your ex - wife. 	 tensor([-0.0016])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing all your things on the phone with your ex - wife. 	 tensor([-0.0009])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
or doing such a sloppy deal with your ex - wife. 	 tensor([-0.0008])
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.4999999907734653 	 0.5547502395439148
&&&&&&&&&@ SUBSETS 	 ################ 's taxes with your############ .</s>
&&&&&&&&&% SUBSETS 	 [['################', "'s taxes with your", '############', '.</s>']]
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I respect that man's taxes with your wife . . . 	 tensor([-5.9337])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
I also share today's taxes with your family and friends. 	 tensor([-4.9514])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Reign the people's taxes with your tax cut bill. 	 tensor([-0.2110])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
Divide your husband's taxes with your husband, Mr. 	 tensor([-0.1444])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
I can guess nothing's taxes with your plan for it. 	 tensor([-0.1254])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Please file your wife's taxes with your state of Minnesota. 	 tensor([-0.0650])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
Take up your employer's taxes with your 401 (k. 	 tensor([-0.0474])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
But check your child's taxes with your local college board. 	 tensor([-0.0249])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Share your spouse's taxes with your ex - partner. 	 tensor([-0.0185])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
Or you do one's taxes with your paychecks. 	 tensor([-0.0011])
#######
... the movie is just a plain old monster .  </s>
OVERALL SENSITIVITY ON THIS DATAPOINT 2.1336763379821244
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.9999999999702747 	 0.7870310084724427
&&&&&&&&&@ SUBSETS 	  ... the movie is just a#### old monster .</s>
&&&&&&&&&% SUBSETS 	 [['... the movie is just a', '####', 'old monster .</s>']]
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a funny old monster. 	 tensor([-7.7216])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a good old monster. 	 tensor([-7.5830])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a great old monster. 	 tensor([-2.3300])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a creepy old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a pretty old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a poor old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
. . . the movie is just a tired old monster. 	 tensor([-0.0008])
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.9999999998649105 	 0.635851410369873
&&&&&&&&&@ SUBSETS 	  ... the movie is######## plain old monster .</s>
&&&&&&&&&% SUBSETS 	 [['... the movie is', '########', 'plain old monster .</s>']]
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is not a plain old monster. 	 tensor([-7.4809])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a pretty plain old monster. 	 tensor([-0.0067])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is a just plain old monster. 	 tensor([-0.0058])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is about a plain old monster. 	 tensor([-0.0040])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
. . . the movie is like that plain old monster. 	 tensor([-0.0009])
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.9999999998647195 	 0.3563696281814575
&&&&&&&&&@ SUBSETS 	  ... the movie is just a plain#### monster .</s>
&&&&&&&&&% SUBSETS 	 [['... the movie is just a plain', '####', 'monster .</s>']]
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain good monster. 	 tensor([-7.7701])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain scary monster. 	 tensor([-0.0417])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain silly monster. 	 tensor([-0.0013])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain old monster. 	 tensor([-0.0010])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain show monster. 	 tensor([-0.0009])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain stupid monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
. . . the movie is just a plain boring monster. 	 tensor([-0.0008])
&&&&&&&&&&& SUBSET SENSITIVITY 	 0.9999999994024173 	 0.3527841922569275
&&&&&&&&&@ SUBSETS 	 ############################ just a plain old monster .</s>
&&&&&&&&&% SUBSETS 	 [['############################', 'just a plain old monster .</s>']]
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
" I think he wasn't just a plain old monster. 	 tensor([-4.7419])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The whole idea is that Obama is just a plain old monster. 	 tensor([-0.0025])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
The woman who died, he was just a plain old monster. 	 tensor([-0.0017])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
If only I could see her rather just a plain old monster. 	 tensor([-0.0013])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
A . The old lady's just a plain old monster. 	 tensor([-0.0012])
So this one that he's just a plain old monster. 	 tensor([-0.0012])
So this one that he's just a plain old monster. 	 tensor([-0.0012])
So this one that he's just a plain old monster. 	 